const test=require('node:test'),assert=require('node:assert/strict');
const {createHotelReadBudget}=require('../lib/hotelReadBudget');
const {HotelRateLimitError,zippiLimit,sendHotelRateLimit,providerLimit}=require('../lib/hotelRateLimit');
const now0=Date.parse('2026-09-10T12:34:20Z');
function rejection(fn){try{fn();assert.fail('Expected limit')}catch(e){assert(e instanceof HotelRateLimitError);return e.metadata}}
for(const [window,env,advance,limit,reset] of [
 ['MINUTE',{HOTELS_RPM:'1'},0,1,'2026-09-10T12:35:20.000Z'],
 ['HOUR',{HOTELS_HOURLY:'1'},60001,1,'2026-09-10T13:00:00.000Z'],
 ['DAY',{HOTELS_DAILY:'1'},3600001,1,'2026-09-11T00:00:00.000Z'],
])test(`structured ${window} reset and deadline`,()=>{let now=now0;const b=createHotelReadBudget({env,now:()=>now});b.provider('private-device','private-provider','DISCOVERY');now+=advance;const m=rejection(()=>b.provider('private-device','private-provider','DISCOVERY'));assert.equal(m.source,'ZIPPI');assert.equal(m.scope,'DISCOVERY');assert.equal(m.window,window);assert.equal(m.limit,limit);assert.equal(m.remaining,0);assert.equal(m.resetAt,reset);assert.equal(m.retryAfterSeconds,Math.ceil((Date.parse(reset)-now)/1000));assert(!JSON.stringify(m).includes('private'));now=Date.parse(reset);b.provider('private-device','private-provider','DISCOVERY')});
test('longest exhausted window is advertised',()=>{let now=now0;const b=createHotelReadBudget({env:{HOTELS_RPM:'1',HOTELS_HOURLY:'1',HOTELS_DAILY:'1'},now:()=>now});b.provider('u','p','DISCOVERY');assert.equal(rejection(()=>b.provider('u','p','DISCOVERY')).window,'DAY')});
test('API reads do not debit provider budget',()=>{const b=createHotelReadBudget({env:{HOTELS_RPM:'10',HOTELS_DAILY:'1'},now:()=>now0});for(let i=0;i<9;i++)b.api('u');b.provider('u','p','DISCOVERY');assert.equal(rejection(()=>b.provider('u','p','DISCOVERY')).window,'DAY')});
test('pricing and discovery share aggregate protection but separate identity operations',()=>{const b=createHotelReadBudget({env:{HOTELS_DAILY:'1'},now:()=>now0});b.provider('u','p','PRICING');const m=rejection(()=>b.provider('u','p','DISCOVERY'));assert.equal(m.scope,'PROVIDER_TOTAL');assert.equal(m.window,'DAY')});
test('aggregate protection spans distinct users',()=>{const b=createHotelReadBudget({env:{HOTELS_RPM:'1'},now:()=>now0});b.provider('a','p','DISCOVERY');assert.equal(rejection(()=>b.provider('b','p','DISCOVERY')).scope,'PROVIDER_TOTAL')});
test('QA policy is server owned, finite, and does not increase provider budget',()=>{const b=createHotelReadBudget({env:{HOTEL_TRAFFIC_CLASS:'QA',HOTELS_RPM:'1',HOTEL_PROVIDER_MINUTE:'999'},now:()=>now0});assert.equal(b.traffic,'QA');b.provider('qa-a','p','DISCOVERY');assert.equal(rejection(()=>b.provider('qa-b','p','DISCOVERY')).limit,1);assert.equal(createHotelReadBudget({env:{}}).traffic,'CONSUMER')});
test('invalid or disabled new budget settings cannot remove finite protection',()=>{const b=createHotelReadBudget({env:{HOTELS_RPM:'-1',HOTEL_PROVIDER_MINUTE:'-1'},now:()=>now0});for(let i=0;i<10;i++)b.provider('u','p','DISCOVERY');assert.equal(rejection(()=>b.provider('u','p','DISCOVERY')).limit,10)});
test('HTTP contract and redaction',()=>{const headers={};let body,status;sendHotelRateLimit({setHeader:(k,v)=>headers[k]=v,status(n){status=n;return this},json(b){body=b}},zippiLimit('DISCOVERY','DAY',100,now0+2000,now0));assert.equal(status,429);assert.equal(body.code,'HOTEL_RATE_LIMITED');assert.equal(headers['Retry-After'],'2');assert.equal(headers['RateLimit-Reset'],'2');assert.equal(body.rateLimit.resetAt,'2026-09-10T12:34:22.000Z');assert.equal(headers['Cache-Control'],'no-store');assert.match(headers['Access-Control-Expose-Headers'],/Retry-After/);assert.equal(body.rateLimit.remaining,0)});
for(const [name,headers,seconds] of [
 ['delta',{'retry-after':'2'},2],['date',{'retry-after':'Thu, 10 Sep 2026 12:34:22 GMT'},2],
 ['reset',{'ratelimit-reset':'Thu, 10 Sep 2026 12:34:25 GMT'},5],['absent',{},undefined],
 ['malformed',{'retry-after':'secret-token','ratelimit-reset':'private@example.com'},undefined],
 ['negative',{'retry-after':'-1'},undefined],['overflow',{'retry-after':'9999999999999999999'},undefined],
])test(`provider ${name} metadata`,()=>{const e=providerLimit(new Headers(headers),'DISCOVERY',now0);assert.equal(e.metadata.source,'PROVIDER');assert.equal(e.metadata.retryAfterSeconds,seconds);assert(!JSON.stringify(e).includes('secret-token'));assert(!JSON.stringify(e).includes('private@example'))});
test('provider clock skew uses server Date and longest actual cooldown',()=>{const e=providerLimit(new Headers({'date':'Thu, 10 Sep 2026 12:34:20 GMT','retry-after':'2','ratelimit-reset':'Thu, 10 Sep 2026 12:34:25 GMT','ratelimit-limit':'10','ratelimit-remaining':'0','authorization':'private'}),'DISCOVERY',now0+50000);assert.equal(e.metadata.retryAfterSeconds,5);assert.equal(e.metadata.limit,10);assert.equal(e.metadata.remaining,0);assert(!JSON.stringify(e).includes('private'))});
