const test=require('node:test'),assert=require('node:assert/strict');
const {createHotelDiscoveryCoalescer}=require('../lib/hotelDiscoveryCoalescer');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}}
test('two waiters share one active operation and finished work is never cached',async()=>{const c=createHotelDiscoveryCoalescer(),d=deferred();let calls=0;const work=()=>{calls++;return d.promise};const a=c.run('same',null,work),b=c.run('same',null,work);await tick();assert.equal(calls,1);d.resolve('inventory');assert.deepEqual(await Promise.all([a,b]),['inventory','inventory']);assert.equal(c.size(),0);await c.run('same',null,work);assert.equal(calls,2)});
test('one caller cancelling leaves shared provider work alive',async()=>{const c=createHotelDiscoveryCoalescer(),d=deferred(),a=new AbortController();let upstream;const first=c.run('same',a.signal,s=>{upstream=s;return d.promise});const second=c.run('same',null,()=>assert.fail());await tick();a.abort();await assert.rejects(first,{name:'AbortError'});assert(!upstream.aborted);d.resolve('result');assert.equal(await second,'result');assert.equal(c.size(),0)});
test('all callers cancelled abort upstream and release entry',async()=>{const c=createHotelDiscoveryCoalescer(),a=new AbortController(),b=new AbortController();const work=s=>new Promise((_,reject)=>s.addEventListener('abort',()=>reject(new Error('cancelled')),{once:true}));const first=c.run('same',a.signal,work),second=c.run('same',b.signal,work);await tick();a.abort();b.abort();await assert.rejects(first,{name:'AbortError'});await assert.rejects(second,{name:'AbortError'});assert.equal(c.size(),0)});
test('already aborted caller never starts provider work',async()=>{const c=createHotelDiscoveryCoalescer(),a=new AbortController();a.abort();await assert.rejects(c.run('same',a.signal,()=>assert.fail()),{name:'AbortError'});assert.equal(c.size(),0)});
test('upstream failure reaches all waiters and cleanup permits a later request',async()=>{const c=createHotelDiscoveryCoalescer(),d=deferred();const first=c.run('same',null,()=>d.promise),second=c.run('same',null,()=>assert.fail());d.reject(new Error('safe failure'));await assert.rejects(first,/safe failure/);await assert.rejects(second,/safe failure/);assert.equal(c.size(),0);assert.equal(await c.run('same',null,()=>42),42)});
test('late cancelled leader cannot remove a newer entry with the same key',async()=>{const c=createHotelDiscoveryCoalescer(),d=deferred(),next=deferred(),a=new AbortController();const first=c.run('same',a.signal,()=>d.promise);await tick();a.abort();await assert.rejects(first);const second=c.run('same',null,()=>next.promise);d.resolve('stale');await tick();assert.equal(c.size(),1);next.resolve('current');assert.equal(await second,'current');assert.equal(c.size(),0)});
