const test=require('node:test'),assert=require('node:assert/strict');
const {createServerHarness,stayResult}=require('../test-support/hotelServerHarness');
const tick=()=>new Promise(r=>setImmediate(r));
const body={city:'Miami',lat:25.76,lng:-80.19,checkIn:'2026-10-15',nights:5,adults:1,max:10};
const result=()=>({data:{results:[stayResult()]}});
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}}
test('real search route coalesces once, debits once, and returns independent mapped responses',async()=>{const d=deferred();const h=createServerHarness({env:{HOTELS_DAILY:'1'},providerResponse:()=>d.promise});const a=h.request('/v1/hotels/search',{body}),b=h.request('/v1/hotels/search',{body:{...body}});await tick();assert.equal(h.providerCalls.length,1);d.resolve(result());const [x,y]=await Promise.all([a,b]);assert.equal(x.status,200);assert.equal(y.status,200);x.body.items[0].name='mutated';assert.notEqual(y.body.items[0].name,'mutated');const next=await h.request('/v1/hotels/search',{body});assert.equal(next.status,429);assert.equal(next.body.rateLimit.window,'DAY');assert.equal(h.providerCalls.length,1)});
for(const [name,change,headers] of [
 ['dates',{checkIn:'2026-10-16'},{}],['city',{city:'Bogota'},{}],['locale',{locale:'es'},{}],['radius',{radiusKm:20},{}],['adults',{adults:2},{}],['nights',{nights:6},{}],['access identity',{}, {'x-user-id':'other-device'}],['verified versus anonymous',{}, {authorization:'Bearer verified-fixture'}]
])test(`different ${name} does not coalesce`,async()=>{const d=deferred();const h=createServerHarness({providerResponse:()=>d.promise});const a=h.request('/v1/hotels/search',{body}),b=h.request('/v1/hotels/search',{body:{...body,...change},headers});await tick();assert.equal(h.providerCalls.length,2);d.resolve(result());assert.deepEqual((await Promise.all([a,b])).map(x=>x.status),[200,200])});
test('coalesced real route preserves surviving caller after cancellation',async()=>{const d=deferred(),controller=new AbortController();const h=createServerHarness({providerResponse:()=>d.promise});const a=h.request('/v1/hotels/search',{body,signal:controller.signal}),b=h.request('/v1/hotels/search',{body});await tick();controller.abort();d.resolve(result());const [x,y]=await Promise.all([a,b]);assert.equal(x.body,null);assert.equal(y.status,200);assert.equal(h.providerCalls.length,1)});
test('photo and local pricing reads do not exhaust discovery daily budget',async()=>{const h=createServerHarness({env:{HOTELS_DAILY:'1'},providerResponse:()=>result()});await h.request('/v1/hotels/photo',{method:'GET',query:{hotelId:'acc_fixture'}});await h.request('/v1/hotels/ping',{method:'GET'});await h.request('/v1/hotels/prices',{body:{hotelIds:['acc_fixture'],checkIn:'2026-10-15',nights:5,adults:1}});assert.equal(h.providerCalls.length,0);assert.equal((await h.request('/v1/hotels/search',{body})).status,200);assert.equal(h.providerCalls.length,1)});
test('pricing provider fetch debits aggregate; cached room read does not',async()=>{const h=createServerHarness({env:{HOTELS_DAILY:'1'},providerResponse:({url})=>url.includes('fetch_all_rates')?{data:stayResult()}:result()});const p={hotelIds:['acc_fixture'],searchResultIds:{acc_fixture:'srr_fixture'},checkIn:'2026-10-15',nights:5,adults:1};assert.equal((await h.request('/v1/hotels/prices',{body:p})).status,200);assert.equal((await h.request('/v1/hotels/prices',{body:p})).status,200);assert.equal(h.providerCalls.length,1);const x=await h.request('/v1/hotels/search',{body});assert.equal(x.status,429);assert.equal(x.body.rateLimit.scope,'PROVIDER_TOTAL')});
for(const [name,env,scope] of [['hotel',{HOTELS_RPM:'1'},'API'],['route',{HOTELS_ROUTE_RPM:'1'},'API_ROUTE'],['global',{GLOBAL_RPM:'1'},'API_GLOBAL']])test(`${name} API abuse limiter still applies with structured reset`,async()=>{const h=createServerHarness({env});await h.request('/v1/hotels/ping',{method:'GET'});const x=await h.request('/v1/hotels/ping',{method:'GET'});assert.equal(x.status,429);assert.equal(x.body.rateLimit.scope,scope);assert.equal(x.body.rateLimit.window,'MINUTE');assert(Number(x.headers['retry-after'])>0)});
test('caller QA/bypass fields cannot avoid API limits',async()=>{const h=createServerHarness({env:{HOTELS_RPM:'1'}});await h.request('/v1/hotels/ping',{method:'GET'});const x=await h.request('/v1/hotels/ping',{method:'GET',body:{bypass:true,qa:true},headers:{'x-qa':'true','x-internal-test':'true'}});assert.equal(x.status,429)});
for(const status of [400,401,403,404,500,502,503])test(`upstream ${status} retains existing HTTP 502 mapping`,async()=>{const h=createServerHarness({providerResponse:()=>({httpStatus:status,body:{error:'fixture'}})});assert.equal((await h.request('/v1/hotels/search',{body})).status,502)});
for(const [name,headers,expected] of [['present',{'retry-after':'2'},'2'],['absent',{},undefined]])test(`upstream 429 ${name} cooldown is propagated without invention`,async()=>{const d=deferred();const h=createServerHarness({providerResponse:()=>d.promise});const a=h.request('/v1/hotels/search',{body}),b=h.request('/v1/hotels/search',{body});await tick();d.resolve({httpStatus:429,headers,body:{errors:[{message:'secret-do-not-echo'}]}});for(const x of await Promise.all([a,b])){assert.equal(x.status,429);assert.equal(x.body.rateLimit.source,'PROVIDER');assert.equal(x.headers['retry-after'],expected);assert(!JSON.stringify(x).includes('secret-do-not-echo'))}assert.equal(h.providerCalls.length,1)});
test('upstream network failure is shared and next search starts fresh',async()=>{const d=deferred();let n=0;const h=createServerHarness({providerResponse:()=>++n===1?d.promise:result()});const a=h.request('/v1/hotels/search',{body}),b=h.request('/v1/hotels/search',{body});await tick();d.reject(new Error('fixture network loss'));assert.deepEqual((await Promise.all([a,b])).map(x=>x.status),[502,502]);assert.equal((await h.request('/v1/hotels/search',{body})).status,200);assert.equal(h.providerCalls.length,2)});
for (const [name,pricingBody] of [
 ['legacy',{hotelIds:['acc_fixture'],searchResultIds:{acc_fixture:'srr_fixture'},checkIn:'2026-10-15',nights:7,adults:2}],
 ['discovery',{discoveryPricing:{hotelId:'acc_fixture',searchResultId:'srr_fixture',rateId:'rat_fixture',checkIn:'2026-10-15',checkOut:'2026-10-22',adults:2,rooms:1,currency:'USD'}}],
]) test(`${name} pricing preserves provider 429 instead of swallowing it`,async()=>{
 const h=createServerHarness({providerResponse:()=>({httpStatus:429,headers:{'retry-after':'4'},body:{error:'private provider details'}})});
 const x=await h.request('/v1/hotels/prices',{body:pricingBody});
 assert.equal(x.status,429);assert.equal(x.body.rateLimit.source,'PROVIDER');assert.equal(x.body.rateLimit.scope,'PRICING');
 assert.equal(x.headers['retry-after'],'4');assert.equal(h.providerCalls.length,1);assert(!JSON.stringify(x).includes('private provider details'));
});
